Business Questions
Which vehicle characteristics have the greatest influence on the listing price of a used car?
How do factors such as mileage, age, accident history, and horsepower affect a vehicle's listing price?
Can a multiple linear regression model accurately estimate the listing price of a used vehicle based on its characteristics?
Can the model identify vehicles whose asking price appears significantly higher or lower than the estimated market value?

In [51]:
import pandas as pd
df = pd.read_csv("../data/processed/used_cars_reduced.csv")
pd.set_option("display.float_format", "{:,.2f}".format)

C:\Users\casey\AppData\Local\Temp\ipykernel_46396\2660379681.py:2: DtypeWarning: Columns (0: dealer_zip) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/used_cars_reduced.csv")

In [52]:
df.drop_duplicates(inplace = True)

In [53]:
df = df.reset_index()

In [54]:
df.shape

(2663251, 22)

In [55]:
df.columns

Index(['index', 'city', 'dealer_zip', 'engine_cylinders', 'engine_type',
       'frame_damaged', 'fuel_type', 'has_accidents', 'horsepower', 'is_new',
       'make_name', 'mileage', 'model_name', 'owner_count', 'price', 'salvage',
       'seller_rating', 'transmission', 'trim_name', 'vehicle_damage_category',
       'wheel_system', 'year'],
      dtype='str')

In [56]:
df.tail()

,index,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,horsepower,is_new,...,model_name,owner_count,price,salvage,seller_rating,transmission,trim_name,vehicle_damage_category,wheel_system,year
2663246,3000035,Fairfield,94533,I4,I4,False,Gasoline,False,170.00,False,...,Equinox,1.00,"17,998.00",False,4.27,A,1.5T LT FWD,NaN,FWD,2018
2663247,3000036,Vallejo,94591,V6,V6,NaN,Gasoline,NaN,310.00,True,...,Traverse,NaN,"36,490.00",NaN,4.53,A,LS FWD,NaN,FWD,2020
2663248,3000037,Napa,94559,NaN,NaN,False,NaN,True,240.00,False,...,Fusion,2.00,"12,990.00",False,4.14,A,SE,NaN,FWD,2016
2663249,3000038,Fairfield,94533,I4 Diesel,I4 Diesel,False,Diesel,False,180.00,False,...,XE,1.00,"26,998.00",False,4.27,A,20d Premium AWD,NaN,AWD,2017
2663250,3000039,Napa,94559,I4,I4,False,Gasoline,False,170.00,False,...,Rogue,1.00,"19,900.00",False,4.33,A,2017.5 SV FWD,NaN,FWD,2017

In [57]:
df.dtypes

index                        int64
city                           str
dealer_zip                  object
engine_cylinders               str
engine_type                    str
frame_damaged               object
fuel_type                      str
has_accidents               object
horsepower                 float64
is_new                        bool
make_name                      str
mileage                    float64
model_name                     str
owner_count                float64
price                      float64
salvage                     object
seller_rating              float64
transmission                   str
trim_name                      str
vehicle_damage_category    float64
wheel_system                   str
year                         int64
dtype: object

In [58]:
df.isna().sum()

index                            0
city                             0
dealer_zip                       0
engine_cylinders             87917
engine_type                  87917
frame_damaged              1096177
fuel_type                    72638
has_accidents              1096177
horsepower                  150591
is_new                           0
make_name                        0
mileage                     102516
model_name                       0
owner_count                1181157
price                            0
salvage                    1096177
seller_rating                38300
transmission                 55013
trim_name                   103002
vehicle_damage_category    2663251
wheel_system                128034
year                             0
dtype: int64

In [59]:
df.shape

(2663251, 22)

In [60]:
df.describe()

,index,horsepower,mileage,owner_count,price,seller_rating,vehicle_damage_category,year
count,"2,663,251.00","2,512,660.00","2,560,735.00","1,482,094.00","2,663,251.00","2,624,951.00",0.00,"2,663,251.00"
mean,"1,492,757.99",251.67,"34,730.86",1.53,"29,724.89",4.28,NaN,"2,017.43"
std,"862,007.48",91.03,"77,967.58",0.92,"20,251.10",0.51,NaN,4.34
min,0.00,55.00,0.00,1.00,165.00,1.00,NaN,"1,915.00"
25%,"749,003.50",176.00,9.00,1.00,"17,681.00",4.03,NaN,"2,017.00"
50%,"1,489,415.00",248.00,"17,880.00",1.00,"26,000.00",4.35,NaN,"2,019.00"
75%,"2,230,800.50",305.00,"49,241.00",2.00,"38,290.00",4.62,NaN,"2,020.00"
max,"3,000,039.00","1,001.00","99,999,988.00",19.00,"3,299,995.00",5.00,NaN,"2,021.00"

In [62]:
df.head()

,index,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,horsepower,is_new,...,model_name,owner_count,price,salvage,seller_rating,transmission,trim_name,vehicle_damage_category,wheel_system,year
0,0,Bayamon,960,I4,I4,NaN,Gasoline,NaN,177.00,True,...,Renegade,NaN,"23,141.00",NaN,2.80,A,Latitude FWD,NaN,FWD,2019
1,1,San Juan,922,I4,I4,NaN,Gasoline,NaN,246.00,True,...,Discovery Sport,NaN,"46,500.00",NaN,3.00,A,S AWD,NaN,AWD,2020
2,2,Guaynabo,969,H4,H4,False,Gasoline,False,305.00,False,...,WRX STI,3.00,"46,995.00",False,NaN,M,Base,NaN,AWD,2016
3,3,San Juan,922,V6,V6,NaN,Gasoline,NaN,340.00,True,...,Discovery,NaN,"67,430.00",NaN,3.00,A,V6 HSE AWD,NaN,AWD,2020
4,4,San Juan,922,I4,I4,NaN,Gasoline,NaN,246.00,True,...,Discovery Sport,NaN,"48,880.00",NaN,3.00,A,S AWD,NaN,AWD,2020

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2663251 entries, 0 to 2663250
Data columns (total 22 columns):
 #   Column                   Dtype
---  ------                   -----
 0   index                    int64
 1   city                     str
 2   dealer_zip               object
 3   engine_cylinders         str
 4   engine_type              str
 5   frame_damaged            object
 6   fuel_type                str
 7   has_accidents            object
 8   horsepower               float64
 9   is_new                   bool
 10  make_name                str
 11  mileage                  float64
 12  model_name               str
 13  owner_count              float64
 14  price                    float64
 15  salvage                  object
 16  seller_rating            float64
 17  transmission             str
 18  trim_name                str
 19  vehicle_damage_category  float64
 20  wheel_system             str
 21  year                     int64
dtypes: bool(1), float64(6), int64(2), object(4), str(9)
memory usage: 429.2+ MB

In [64]:
df.drop("vehicle_damage_category", axis=1, inplace=True)

In [65]:
numerical_data = df.select_dtypes(include=["number"]).columns.tolist()
categorical_data = df.select_dtypes(include=["object", "string", "bool"]).columns.tolist()

In [66]:
numerical_data

['index',
 'horsepower',
 'mileage',
 'owner_count',
 'price',
 'seller_rating',
 'year']

In [67]:
categorical_data

['city',
 'dealer_zip',
 'engine_cylinders',
 'engine_type',
 'frame_damaged',
 'fuel_type',
 'has_accidents',
 'is_new',
 'make_name',
 'model_name',
 'salvage',
 'transmission',
 'trim_name',
 'wheel_system']

Data Cleaning Candidates", and add:

1.Drop all duplicates 
2. Remove vehicle_damage_category (100% missing).
3.Investigate or treat implausible mileage values (>1,000,000).
4.Investigate missing values in frame_damaged, has_accidents, salvage, and owner_count.
5.Does dealer_zip add meaningful information beyond city, or is it mostly redundant?
are engine cylinder matching engine-type?
6.Later, during feature engineering, ill group infrequent trims because thousands of unique categories can be difficult for a simple linear regression model.
7.Drop engine cylinders because it is identical to engine type
8.

In [68]:
df[numerical_data].describe()

,index,horsepower,mileage,owner_count,price,seller_rating,year
count,"2,663,251.00","2,512,660.00","2,560,735.00","1,482,094.00","2,663,251.00","2,624,951.00","2,663,251.00"
mean,"1,492,757.99",251.67,"34,730.86",1.53,"29,724.89",4.28,"2,017.43"
std,"862,007.48",91.03,"77,967.58",0.92,"20,251.10",0.51,4.34
min,0.00,55.00,0.00,1.00,165.00,1.00,"1,915.00"
25%,"749,003.50",176.00,9.00,1.00,"17,681.00",4.03,"2,017.00"
50%,"1,489,415.00",248.00,"17,880.00",1.00,"26,000.00",4.35,"2,019.00"
75%,"2,230,800.50",305.00,"49,241.00",2.00,"38,290.00",4.62,"2,020.00"
max,"3,000,039.00","1,001.00","99,999,988.00",19.00,"3,299,995.00",5.00,"2,021.00"

In [69]:
df[df["mileage"] == df["mileage"].max()]

,index,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,horsepower,is_new,...,mileage,model_name,owner_count,price,salvage,seller_rating,transmission,trim_name,wheel_system,year
2242507,2514282,Houston,77065,I6 Diesel,I6 Diesel,NaN,Diesel,NaN,NaN,True,...,"99,999,988.00",3500 Chassis,NaN,"52,610.00",NaN,3.57,A,NaN,NaN,2019

In [ ]:
#Several extremely large mileage values (e.g., 1,111,111 and 99,999,988) appear to be placeholder or #
#erroneous values rather than genuine odometer readings. 
#Further investigation or consultation of the dataset documentation is recommended before deciding how to treat these records.
df[df["mileage"] > 1_000_000]

,index,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,horsepower,is_new,...,mileage,model_name,owner_count,price,salvage,seller_rating,transmission,trim_name,wheel_system,year
185063,210044,Nappanee,46550,V8,V8,NaN,Gasoline,NaN,355.00,True,...,"4,290,461.00",Silverado 1500,NaN,"50,775.00",NaN,5.00,A,LT Crew Cab 4WD,4WD,2020
1180953,1319359,Belleview,34420,V6,V6,NaN,Gasoline,NaN,375.00,True,...,"1,225,238.00",F-150,NaN,"45,149.00",NaN,4.50,A,XLT SuperCrew RWD,4X2,2020
1853005,2072522,Boise,83713,V8,V8,NaN,Gasoline,NaN,355.00,True,...,"1,111,111.00",Silverado 1500,NaN,"39,523.00",NaN,3.82,A,LT Double Cab 4WD,4WD,2020
1853098,2072617,Boise,83713,I4,I4,NaN,Gasoline,NaN,170.00,True,...,"1,111,111.00",Equinox,NaN,"23,620.00",NaN,3.82,A,1.5T LT AWD,4WD,2020
1853986,2073566,Boise,83713,V8,V8,NaN,Gasoline,NaN,355.00,True,...,"1,111,111.00",Silverado 1500,NaN,"41,420.00",NaN,3.82,A,LT Double Cab 4WD,4WD,2020
1855598,2075306,Boise,83713,I4,I4,NaN,Gasoline,NaN,237.00,True,...,"1,111,111.00",XT5,NaN,"45,970.00",NaN,3.82,A,Luxury AWD,4WD,2020
2242507,2514282,Houston,77065,I6 Diesel,I6 Diesel,NaN,Diesel,NaN,NaN,True,...,"99,999,988.00",3500 Chassis,NaN,"52,610.00",NaN,3.57,A,NaN,NaN,2019

Seven records contain implausibly large mileage values (>1,000,000). Several share identical values (e.g., 1,111,111), suggesting placeholder or erroneous entries rather than genuine odometer readings. These records will require special treatment during data cleaning.

In [76]:
df[df["owner_count"]  > 10]

,index,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,horsepower,is_new,...,mileage,model_name,owner_count,price,salvage,seller_rating,transmission,trim_name,wheel_system,year
39261,44751,Lodi,7644,V8,V8,False,Gasoline,False,170.00,False,...,"104,655.00",Brougham,12.00,"3,995.00",False,3.89,A,RWD,RWD,1991
50831,57580,Bloomfield,7003,V8,V8,False,Gasoline,False,300.00,False,...,"203,000.00",F-150,11.00,"7,999.00",False,4.56,A,FX4 Ext. Cab SB 4WD,4WD,2004
67287,75922,Macomb,48042,V8,V8,False,Gasoline,False,180.00,False,...,"46,965.00",Monte Carlo,15.00,"24,990.00",False,4.76,A,SS RWD,RWD,1987
94271,106661,Somerville,2143,I5,I5,False,Gasoline,False,168.00,False,...,"193,131.00",S40,11.00,"3,995.00",False,4.45,M,2.4i,FWD,2005
172760,195450,Warsaw,46582,I4,I4,False,Gasoline,False,115.00,False,...,"157,225.00",Beetle,11.00,"4,999.00",False,4.62,NaN,2 Dr GLS Hatchback,FWD,1999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2535149,2850569,Spring Valley,91977,I6,I6,False,Gasoline,False,181.00,False,...,"109,000.00",Wrangler,11.00,"12,995.00",False,5.00,A,Sport,4WD,1998
2552437,2870450,Canoga Park,91303,I4,I4,False,Gasoline,True,115.00,False,...,"202,356.00",Civic Coupe,11.00,"1,999.00",False,4.00,A,LX,FWD,2001
2623307,2953461,Sunnyvale,94085,I4,I4,False,Gasoline,False,122.00,False,...,"102,700.00",Versa,11.00,"5,500.00",False,NaN,A,S 1.8,FWD,2009
2632136,2963675,Santa Clara,95051,I4,I4,False,Gasoline,False,126.00,False,...,"143,112.00",Wrangler,11.00,"8,999.00",False,4.50,M,S,4WD,1991
2633905,2965812,Fremont,94536,I6,I6,False,Gasoline,False,208.00,False,...,"238,744.00",5 Series,16.00,"5,500.00",False,4.00,M,535i Sedan RWD,RWD,1991

Owner count exhibits a negative association with vehicle price and a positive association with mileage. Vehicles with more previous owners also tend to be older, suggesting that owner count is correlated with both vehicle age and usage. The feature appears informative and will be retained for model training, while recognizing that its effect may overlap with other predictors such as year and mileage.

In [77]:
df["owner_count"].value_counts().sort_index()

owner_count
1.00     972156
2.00     330478
3.00     116768
4.00      39764
5.00      14207
6.00       5286
7.00       1977
8.00        836
9.00        366
10.00       128
11.00        73
12.00        21
13.00        16
14.00         7
15.00         6
16.00         3
18.00         1
19.00         1
Name: count, dtype: int64

In [78]:
df["owner_count"].isna().sum()

np.int64(1181157)

In [79]:
df[df["owner_count"] == 19]

,index,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,horsepower,is_new,...,mileage,model_name,owner_count,price,salvage,seller_rating,transmission,trim_name,wheel_system,year
859385,962449,Mt Sterling,40353,V8,V8,False,Gasoline,True,220.00,False,...,"126,611.00",RAM 1500,19.00,"3,694.00",False,4.22,A,LT 4WD,4WD,1997

In [80]:
df.groupby("owner_count")["price"].mean()

owner_count
1.00    25,225.62
2.00    17,941.32
3.00    14,317.36
4.00    12,710.21
5.00    12,016.20
6.00    12,050.94
7.00    13,296.37
8.00    11,726.27
9.00    13,394.89
10.00   10,739.07
11.00   10,024.23
12.00    5,798.00
13.00    7,630.50
14.00   12,681.43
15.00   10,176.50
16.00   10,774.67
18.00    6,999.00
19.00    3,694.00
Name: price, dtype: float64

In [81]:
df.groupby("owner_count")["mileage"].mean()

owner_count
1.00     41,882.28
2.00     81,649.54
3.00    105,846.50
4.00    121,851.00
5.00    132,584.19
6.00    139,110.61
7.00    141,454.55
8.00    144,748.62
9.00    151,364.29
10.00   146,067.66
11.00   156,307.33
12.00   155,633.69
13.00   196,052.38
14.00   119,815.17
15.00   180,124.60
16.00   244,811.67
18.00   211,192.00
19.00   126,611.00
Name: mileage, dtype: float64

In [82]:
df.groupby("owner_count")["year"].mean()

owner_count
1.00    2,017.07
2.00    2,013.85
3.00    2,011.30
4.00    2,009.16
5.00    2,007.19
6.00    2,005.50
7.00    2,003.96
8.00    2,002.79
9.00    2,001.91
10.00   2,000.38
11.00   1,999.11
12.00   1,998.38
13.00   1,997.19
14.00   1,994.00
15.00   1,995.50
16.00   1,994.67
18.00   1,995.00
19.00   1,997.00
Name: year, dtype: float64

In [83]:
df[numerical_data].corr()

,index,horsepower,mileage,owner_count,price,seller_rating,year
index,1.00,0.03,-0.01,0.01,0.03,0.00,0.03
horsepower,0.03,1.00,-0.05,0.00,0.60,0.05,0.06
mileage,-0.01,-0.05,1.00,0.52,-0.28,0.01,-0.46
owner_count,0.01,0.00,0.52,1.00,-0.23,0.01,-0.59
price,0.03,0.60,-0.28,-0.23,1.00,0.06,0.37
seller_rating,0.00,0.05,0.01,0.01,0.06,1.00,-0.04
year,0.03,0.06,-0.46,-0.59,0.37,-0.04,1.00

In [84]:
df[numerical_data].skew()

index             0.01
horsepower        0.67
mileage         823.52
owner_count       2.47
price            14.78
seller_rating    -1.54
year             -4.43
dtype: float64

In [71]:
df[categorical_data].describe()

,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,is_new,make_name,model_name,salvage,transmission,trim_name,wheel_system
count,2663251,2663251,2575334,2575334,1567074,2590613,1567074,2663251,2663251,2663251,1567074,2608238,2560249,2535217
unique,4687,10411,39,39,2,8,2,2,100,1429,2,4,9062,5
top,Houston,77477,I4,I4,False,Gasoline,False,False,Ford,F-150,False,A,SE FWD,FWD
freq,37446,7058,1216031,1216031,1552123,2297701,1324168,1527324,442252,119058,1556555,2193284,72751,1082600

engine_type and engine_cylinders contain identical information, including matching missing values (.equals() returned True). Therefore, engine_cylinders is redundant and can be removed during feature engineering to eliminate duplicate information.

In [72]:
(df["engine_type"] == df["engine_cylinders"]).all()

np.False_

In [73]:
df[df["engine_type"] != df["engine_cylinders"]]

,index,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,horsepower,is_new,...,mileage,model_name,owner_count,price,salvage,seller_rating,transmission,trim_name,wheel_system,year
42,42,Bronx,10466,NaN,NaN,False,NaN,False,180.00,False,...,"15,778.00",Renegade,1.00,"16,200.00",False,2.80,A,Altitude 4WD,4WD,2017
50,50,Bronx,10466,NaN,NaN,False,NaN,False,NaN,False,...,"19,801.00",Impreza,1.00,"17,300.00",False,2.80,CVT,2.0i Touring Wagon AWD,NaN,2018
61,61,Bronx,10466,NaN,NaN,False,NaN,False,283.00,False,...,"57,995.00",200,3.00,"6,500.00",False,2.80,A,Touring Sedan FWD,FWD,2013
112,112,Bronx,10466,NaN,NaN,False,NaN,False,360.00,False,...,"42,942.00",Grand Cherokee,1.00,"33,700.00",False,2.80,A,Trailhawk 4WD,4WD,2019
215,217,Bronx,10466,NaN,NaN,False,NaN,False,395.00,False,...,"38,602.00",1500,2.00,"48,700.00",False,2.80,A,Laramie Longhorn Crew Cab 4WD,4WD,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2663086,2999874,Fairfield,94533,NaN,NaN,False,Electric,False,NaN,False,...,"31,540.00",Bolt EV,1.00,"17,998.00",False,4.27,A,Premier FWD,FWD,2017
2663094,2999882,Ukiah,95482,NaN,NaN,False,Electric,True,NaN,False,...,"33,921.00",Bolt EV,1.00,"19,479.00",False,4.53,A,Premier FWD,FWD,2017
2663131,2999919,Fairfield,94533,NaN,NaN,False,Electric,False,NaN,False,...,"14,247.00",LEAF,1.00,"9,599.00",False,4.27,A,S,FWD,2016
2663161,2999949,Fairfield,94533,NaN,NaN,False,Electric,False,NaN,False,...,"15,588.00",LEAF,1.00,"9,599.00",False,4.27,A,S,FWD,2016
2663248,3000037,Napa,94559,NaN,NaN,False,NaN,True,240.00,False,...,"57,992.00",Fusion,2.00,"12,990.00",False,4.14,A,SE,FWD,2016

In [75]:
df["engine_type"].equals (df["engine_cylinders"])

True

In [85]:
df['salvage']

0            NaN
1            NaN
2          False
3            NaN
4            NaN
           ...
2663246    False
2663247      NaN
2663248    False
2663249    False
2663250    False
Name: salvage, Length: 2663251, dtype: object

In [86]:
df["salvage"].value_counts(dropna=False)

salvage
False    1556555
NaN      1096177
True       10519
Name: count, dtype: int64

In [89]:
df.groupby("salvage")["price"].mean()

salvage
False   23,215.90
True    13,737.68
Name: price, dtype: float64

In [87]:
df.groupby("has_accidents")["price"].mean()

has_accidents
False   24,300.46
True    16,893.12
Name: price, dtype: float64

In [88]:
df["has_accidents"].value_counts(dropna=False)

has_accidents
False    1324168
NaN      1096177
True      242906
Name: count, dtype: int64