In [4]:
import pandas as pd
df = pd.read_csv("../data/raw/us-dealers-used.csv")

C:\Users\casey\AppData\Local\Temp\ipykernel_29660\3192532912.py:2: DtypeWarning: Columns (0: zip) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/us-dealers-used.csv")

In [5]:
df

,id,vin,price,miles,stock_no,year,make,model,trim,body_type,...,drivetrain,transmission,fuel_type,engine_size,engine_block,seller_name,street,city,state,zip
0,38b2f52e-8f5d,1GCWGFCF3F1284719,20998.0,115879.0,W1T503168C,2015.0,Chevrolet,Express Cargo,Work Van,Cargo Van,...,RWD,Automatic,E85 / Unleaded,4.8,V,nissan ellicott city,8569 Baltimore National Pike,Ellicott City,MD,21043
1,97ba4955-ccf0,WBY7Z8C59JVB87514,27921.0,7339.0,P33243,2018.0,BMW,i3,s,Hatchback,...,RWD,Automatic,Electric / Premium Unleaded,0.6,I,hendrick honda pompano beach,5381 N Federal Highway,Pompano Beach,FL,33064
2,be1da9fd-0f34,ML32F4FJ2JHF10325,11055.0,39798.0,WM2091A,2018.0,Mitsubishi,Mirage G4,SE,Sedan,...,FWD,Automatic,Unleaded,1.2,I,russ darrow toyota,2700 West Washington St.,West Bend,WI,53095
3,84327e45-6cb6,1GCPTEE15K1291189,52997.0,28568.0,9U2Y425A,2019.0,Chevrolet,Colorado,ZR2,Pickup,...,4WD,Automatic,Diesel,2.8,I,young kia,308 North Main Street,Layton,UT,84041
4,cde691c3-91dd,1G2AL18F087312093,NaN,188485.0,T36625A,2008.0,Pontiac,G5,Base,Coupe,...,FWD,Automatic,Unleaded,2.2,I,pappas toyota,10011 Spencer Rd,Saint Peters,MO,63376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104299,d02aa41a-4033,1FT7W2BT4KEF92394,69900.0,15270.0,AJ2815,2019.0,Ford,F-250 Super Duty,Lariat,Pickup,...,4WD,Automatic,Diesel,6.7,V,crain kia of fayetteville,3195 N College Avenue,Fayetteville,AR,72703
7104300,987f3ec1-077a,1FT7W2BT0BEB86340,32991.0,143026.0,G581210A,2011.0,Ford,F-250 Super Duty,King Ranch,Pickup,...,4WD,Automatic,Diesel,6.7,V,morgan auto group,3031 N Rocky Point Dr W 770,Tampa,FL,33607
7104301,f117918b-ab31,1FT7W2BT8MEC02433,82900.0,3686.0,210213A,2021.0,Ford,F-250 Super Duty,King Ranch,Pickup,...,4WD,Automatic,Diesel,6.7,V,tindol ford,1901 East Franklin Boulevard,Gastonia,NC,28054
7104302,86c89eea-b050,1FT7W2BT2KED70999,59995.0,39111.0,P6336,2019.0,Ford,F-250 Super Duty,XLT,Pickup,...,4WD,Automatic,Diesel,6.7,V,schicker chrysler dodge jeep ram,5824 Highway 100,Washington,MO,63090
7104303,73b8c7c4-d061,1FT7W2BT8KEG61524,74985.0,18486.0,8U61524,2019.0,Ford,F-250 Super Duty,Lariat,Pickup,...,4WD,Automatic,Diesel,6.7,V,autofarm price ford,811 Westwood Boulevard,Price,UT,84501

In [6]:
df.columns

Index(['id', 'vin', 'price', 'miles', 'stock_no', 'year', 'make', 'model',
       'trim', 'body_type', 'vehicle_type', 'drivetrain', 'transmission',
       'fuel_type', 'engine_size', 'engine_block', 'seller_name', 'street',
       'city', 'state', 'zip'],
      dtype='str')

In [12]:
Delete_cols = ['id', 'stock_no', 'seller_name', 'street']

df.drop(columns=Delete_cols, inplace=True)

In [13]:
df

,vin,price,miles,year,make,model,trim,body_type,vehicle_type,drivetrain,transmission,fuel_type,engine_size,engine_block,city,state,zip
0,1GCWGFCF3F1284719,20998.0,115879.0,2015.0,Chevrolet,Express Cargo,Work Van,Cargo Van,Truck,RWD,Automatic,E85 / Unleaded,4.8,V,Ellicott City,MD,21043
1,WBY7Z8C59JVB87514,27921.0,7339.0,2018.0,BMW,i3,s,Hatchback,Car,RWD,Automatic,Electric / Premium Unleaded,0.6,I,Pompano Beach,FL,33064
2,ML32F4FJ2JHF10325,11055.0,39798.0,2018.0,Mitsubishi,Mirage G4,SE,Sedan,Car,FWD,Automatic,Unleaded,1.2,I,West Bend,WI,53095
3,1GCPTEE15K1291189,52997.0,28568.0,2019.0,Chevrolet,Colorado,ZR2,Pickup,Truck,4WD,Automatic,Diesel,2.8,I,Layton,UT,84041
4,1G2AL18F087312093,NaN,188485.0,2008.0,Pontiac,G5,Base,Coupe,Car,FWD,Automatic,Unleaded,2.2,I,Saint Peters,MO,63376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104299,1FT7W2BT4KEF92394,69900.0,15270.0,2019.0,Ford,F-250 Super Duty,Lariat,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,Fayetteville,AR,72703
7104300,1FT7W2BT0BEB86340,32991.0,143026.0,2011.0,Ford,F-250 Super Duty,King Ranch,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,Tampa,FL,33607
7104301,1FT7W2BT8MEC02433,82900.0,3686.0,2021.0,Ford,F-250 Super Duty,King Ranch,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,Gastonia,NC,28054
7104302,1FT7W2BT2KED70999,59995.0,39111.0,2019.0,Ford,F-250 Super Duty,XLT,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,Washington,MO,63090
7104303,1FT7W2BT8KEG61524,74985.0,18486.0,2019.0,Ford,F-250 Super Duty,Lariat,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,Price,UT,84501

In [20]:
df.drop_duplicates(inplace = True)

In [21]:
(df['price'] > 150000).value_counts()

price
False    5045735
True        7434
Name: count, dtype: int64

In [54]:
df.drop_duplicates(subset="vin", keep="first", inplace=True)

In [55]:
df["vin"].duplicated().sum()

np.int64(0)

In [56]:
df

,vin,price,miles,year,make,model,trim,body_type,vehicle_type,drivetrain,transmission,fuel_type,engine_size,engine_block,city,state,zip
0,1GCWGFCF3F1284719,20998.0,115879.0,2015.0,Chevrolet,Express Cargo,Work Van,Cargo Van,Truck,RWD,Automatic,E85 / Unleaded,4.8,V,Ellicott City,MD,21043
1,WBY7Z8C59JVB87514,27921.0,7339.0,2018.0,BMW,i3,s,Hatchback,Car,RWD,Automatic,Electric / Premium Unleaded,0.6,I,Pompano Beach,FL,33064
2,ML32F4FJ2JHF10325,11055.0,39798.0,2018.0,Mitsubishi,Mirage G4,SE,Sedan,Car,FWD,Automatic,Unleaded,1.2,I,West Bend,WI,53095
3,1GCPTEE15K1291189,52997.0,28568.0,2019.0,Chevrolet,Colorado,ZR2,Pickup,Truck,4WD,Automatic,Diesel,2.8,I,Layton,UT,84041
4,1G2AL18F087312093,NaN,188485.0,2008.0,Pontiac,G5,Base,Coupe,Car,FWD,Automatic,Unleaded,2.2,I,Saint Peters,MO,63376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104276,1FT7W2BT2JEC39568,NaN,123214.0,2018.0,Ford,F-250 Super Duty,Limited,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,Addison,TX,75001
7104279,1FT7W2BT4JEC88013,58994.0,18874.0,2018.0,Ford,F-250 Super Duty,XLT,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,Chicago,IL,60641
7104290,1FT7W2BT3EEA33519,NaN,48646.0,2014.0,Ford,F-250 Super Duty,Lariat,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,Redlands,CA,92373
7104292,1FT7W2BT8BEA10040,27900.0,208144.0,2011.0,Ford,F-250 Super Duty,Lariat,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,White Pine,TN,37890
7104297,1FD7W2BT0KEC89883,52880.0,67601.0,2019.0,Ford,F-250 Super Duty,XL,Pickup,Truck,4WD,Automatic,Diesel,6.7,V,Ephrata,WA,98823

In [57]:
for threshold in [150_000, 250_000, 500_000]:
    print(
        threshold,
        (df["price"] > threshold).sum()
    )

150000 3754
250000 1287
500000 97

In [67]:
Expensive_cars = df.loc[
    df["price"] > 250_000,
    ["vin","price", "year", "make", "model", "trim", "miles"]
]

In [68]:
(Expensive_cars['make']).value_counts()

make
Ferrari          388
Lamborghini      284
Rolls-Royce      203
McLaren          136
Porsche          124
Mercedes-Benz     61
Bentley           61
Aston Martin      20
Ford               8
Maserati           1
Lotus              1
Name: count, dtype: int64

In [69]:
(Expensive_cars['vin']).nunique()

1287

In [60]:
Ferrari = df.loc[(df['make'] == 'Ferrari') &
                (df['price'] > 250000),
                        ["vin", "price", "year", "make", "model", "trim", "miles"]     ]

In [61]:
Ferrari

,vin,price,year,make,model,trim,miles
122,ZFF83CLA8K0243317,395990.0,2019.0,Ferrari,812,Base,4892.0
207,ZFF78VHA0F0213610,679985.0,2015.0,Ferrari,458 Speciale A,Base,1299.0
301,ZFF82WNA5K0238206,330000.0,2019.0,Ferrari,488,GTC4Lusso,3298.0
387,ZFF83CLA4K0245291,357900.0,2019.0,Ferrari,812,Base,1662.0
407,ZFF74UFAXF0206057,269900.0,2015.0,Ferrari,F12berlinetta,Base,9419.0
...,...,...,...,...,...,...,...
5393962,ZFF80AMA6J0236022,299900.0,2018.0,Ferrari,488 Spider,Base,5000.0
5398751,ZFF80AMA8H0228613,280000.0,2017.0,Ferrari,488 Spider,Base,5500.0
5400920,ZFF80AMA4H0225465,299999.0,2017.0,Ferrari,488 Spider,Spider,1975.0
5402118,ZFF80AMA6H0220283,273999.0,2017.0,Ferrari,488 Spider,Base,5247.0
5404889,ZFF82WNA9J0232553,295000.0,2018.0,Ferrari,NaN,GTC4Lusso,1283.0

In [62]:
Ferrari['vin'].nunique()

388